import type {Metadata} from 'next';
import {Sora} from 'next/font/google';
import './globals.css';
import NavBar from '@/components/NavBar';
import {AllPokemonProvider} from '@/context/AllPokemonContext';
import Footer from '@/components/Footer';
import {AuthProvider} from '@/context/AuthContext';
import PageTransition from '@/components/PageTransition';

const sora = Sora({subsets: ['latin'], weight: ['400', '700']});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
};

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className={`${sora.className} h-full antialiased `}>
            <body className="flex h-screen flex-col overflow-hidden bg-tertiary">
                <AuthProvider>
                    <NavBar />

                    <AllPokemonProvider>
                        <main className="flex min-h-0 flex-1 overflow-hidden bg-tertiary">
                            <PageTransition>{children}</PageTransition>
                        </main>
                    </AllPokemonProvider>

                    <Footer />
                </AuthProvider>
            </body>
        </html>
    );
}
