import type {Metadata} from 'next';
import {Sora} from 'next/font/google';
import './globals.css';
import NavBar from '@/components/NavBar';
import {AllPokemonProvider} from '@/context/AllPokemonContext';
import Footer from '@/components/Footer';
import {AuthProvider} from '@/context/AuthContext';

const sora = Sora({subsets: ['latin'], weight: ['400', '700']});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
};

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className={`${sora.className} h-full antialiased`}>
            <body className="h-full flex flex-col bg-primary">
                <AuthProvider>
                    <NavBar />
                    <main className="flex-1 flex flex-col items-center bg-primary">
                        <AllPokemonProvider>{children}</AllPokemonProvider>
                    </main>
                    <Footer />
                </AuthProvider>
            </body>
        </html>
    );
}
